pipeline {
    agent any
    
    stages {
        stage('Run Project 1 Pipeline') {
            steps {
                dir('emman-stuff/project-1') {
                    echo "Running Project 1 pipeline"
                    script {
                        def project1Pipeline = load('Jenkinsfile')
                        project1Pipeline.execute()
                    }
                }
            }
        }
        
        stage('Run Project 2 Pipeline') {
            steps {
                dir('emman-stuff/project-2') {
                    echo "Running Project 2 pipeline"
                    script {
                        def project2Pipeline = load('Jenkinsfile')
                        project2Pipeline.execute()
                    }
                }
            }
        }
    }
}
