@Library('venti-lib')_
import jenkins.model.*

pipeline {
    agent {
        kubernetes {
            // yamlFile 'agent/swag2.yaml'
            yamlFile 'emman-stuff/project-2/agent/swag2.yaml'
        }
    }

    parameters {
        string(name:'num1', defaultValue: '789', description: 'Number picked') 
    }

    stages {
        stage('printStage') {
            steps {
                container('lebron'){
                    sh "echo ${params.num1} | python3.6 /myApp/hello-world.py"
                }
            }
        }
    }
}